### ISSUE TITLE
Improve the visual effect

### ISSUE THREAD

**Issue by neozhaoliang** [charlymarchiaro/magic-square-dance#1]
Hi, this is a very nice animation of domino shuffling algorrithm, with clean and beautiful UI. I'd like to reuse your UI system to make some other stuff. (I have a bunch of math anim ideas to try out)

Just a minor suggestion on improving the visual effect: the edges of adjacent dominoes are overlapping, hence causes some darkening stoke effect. You can try add some margin between adjacent dominos, by "shrink" each domino a liitle. For example assuming your domino is 1x2 in size, you can draw them as 0.9x1.9 rectangles, and use the 0.1 margin for edge strokes. Also it would be better if the edge color is set to white or transparent.

You can see an example of this here: https://www.shadertoy.com/view/Wldyzj

**Comment by charlymarchiaro** [comment]
Hi, thanks for the suggestion, I'll try to fix it. 
You can use it, of course! I'd be very glad if you do.

**Comment by charlymarchiaro** [comment]
I think it looks a little bit better now.
